<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Adds context_text column for Contextual Retrieval feature.
     * This stores the LLM-generated context that explains what the chunk
     * is about in relation to the full document.
     *
     * The embedding will be generated from: context_text + content (concatenated)
     */
    public function up(): void
    {
        Schema::table('document_chunks', function (Blueprint $table) {
            // Context text generated by LLM to provide document-level context
            // Example: "This chunk discusses pricing for product ABC from the company catalog."
            $table->text('context_text')->nullable()->after('content');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('document_chunks', function (Blueprint $table) {
            $table->dropColumn('context_text');
        });
    }
};
